-- Seed inicial para business_awards_import_staging
-- Fuente editorial: anexo interno Michelin Mexico 2026
-- Ejecutar despues de create_business_awards_system.sql

TRUNCATE TABLE business_awards_import_staging;

INSERT INTO business_awards_import_staging (
  raw_name, country, state, city, address, category, subcategory, cuisine_type,
  award_year, stars, green_award, is_new_year, badge_type, badge_text, icon_key,
  search_aliases, source_url, verification_status, notes
) VALUES
('Pujol', 'MX', 'Ciudad de Mexico', 'Ciudad de Mexico', 'Tennyson 133, Polanco, Miguel Hidalgo, CP 11550', 'restaurantes', 'fine_dining', 'Mexicana, Cocina moderna', 2026, 2, FALSE, FALSE, 'michelin_star', '2 Estrellas MICHELIN 2026', 'gold_double_star', ARRAY['pujol','michelin cdmx','fine dining polanco'], 'https://guide.michelin.com/', 'verified', 'Sucursal premiada confirmada.'),
('Quintonil', 'MX', 'Ciudad de Mexico', 'Ciudad de Mexico', 'Isaac Newton 55, Polanco, Miguel Hidalgo, CP 11560', 'restaurantes', 'fine_dining', 'Mexicana, Contemporanea', 2026, 2, FALSE, FALSE, 'michelin_star', '2 Estrellas MICHELIN 2026', 'gold_double_star', ARRAY['quintonil','michelin polanco','fine dining cdmx'], 'https://guide.michelin.com/', 'verified', ''),
('Gaba', 'MX', 'Ciudad de Mexico', 'Ciudad de Mexico', 'Av. Mazatlan 190, Colonia Condesa, Cuauhtemoc, CP 06170', 'restaurantes', 'fine_dining', 'Mexicana', 2026, 1, FALSE, TRUE, 'michelin_star', '1 Estrella MICHELIN 2026 | Nuevo 2026', 'gold_star', ARRAY['gaba','michelin condesa','nuevo michelin 2026 cdmx'], 'https://guide.michelin.com/', 'verified', 'Nuevo en 2026.'),
('La Once Mil', 'MX', 'Ciudad de Mexico', 'Ciudad de Mexico', 'Monte Everest 780, Lomas de Chapultepec, Miguel Hidalgo, CP 11000', 'restaurantes', 'fine_dining', 'Mexicana, Tacos', 2026, 1, FALSE, TRUE, 'michelin_star', '1 Estrella MICHELIN 2026 | Nuevo 2026', 'gold_star', ARRAY['la once mil','tacos michelin cdmx','nuevo michelin lomas'], 'https://guide.michelin.com/', 'verified', 'Nuevo en 2026.'),
('Em', 'MX', 'Ciudad de Mexico', 'Ciudad de Mexico', 'Tonala 133, Roma Norte, Cuauhtemoc, CP 06700', 'restaurantes', 'fine_dining', 'Mexicana, Contemporanea', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['em','michelin roma norte','alta cocina roma norte'], 'https://guide.michelin.com/', 'verified', ''),
('Esquina Comun', 'MX', 'Ciudad de Mexico', 'Ciudad de Mexico', 'Fernando Montes de Oca 86, Condesa, Cuauhtemoc, CP 06140', 'restaurantes', 'fine_dining', 'Mexicana, Creativa', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['esquina comun','michelin condesa','restaurante premiado condesa'], 'https://guide.michelin.com/', 'verified', ''),
('Expendio de Maiz', 'MX', 'Ciudad de Mexico', 'Ciudad de Mexico', 'Av. Yucatan 84, Roma Norte, Cuauhtemoc, CP 06700', 'restaurantes', 'fine_dining', 'Mexicana', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['expendio de maiz','michelin roma','maiz michelin cdmx'], 'https://guide.michelin.com/', 'verified', ''),
('Masala y Maiz', 'MX', 'Ciudad de Mexico', 'Ciudad de Mexico', 'C. Articulo 123 116, Colonia Centro, Cuauhtemoc, CP 06040', 'restaurantes', 'fine_dining', 'Fusion mexicana, india y africana', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['masala y maiz','fusion michelin cdmx','restaurante indio africano mexico'], 'https://guide.michelin.com/', 'verified', ''),
('Maximo', 'MX', 'Ciudad de Mexico', 'Ciudad de Mexico', 'Alvaro Obregon 65 Bis, Roma Norte, Cuauhtemoc, CP 06700', 'restaurantes', 'fine_dining', 'Mexicana', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['maximo','michelin roma norte','fine dining alvaro obregon'], 'https://guide.michelin.com/', 'verified', ''),
('Rosetta', 'MX', 'Ciudad de Mexico', 'Ciudad de Mexico', 'Colima 166, Roma Norte, Cuauhtemoc, CP 06700', 'restaurantes', 'fine_dining', 'Creativa, Mexicana', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['rosetta','michelin roma','alta cocina colima'], 'https://guide.michelin.com/', 'verified', ''),
('Sud 777', 'MX', 'Ciudad de Mexico', 'Ciudad de Mexico', 'Blvd. de la Luz 777, Jardines del Pedregal, Alvaro Obregon, CP 01900', 'restaurantes', 'fine_dining', 'Creativa, Mexicana contemporanea', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['sud 777','michelin pedregal','fine dining sur cdmx'], 'https://guide.michelin.com/', 'verified', ''),
('Alcalde', 'MX', 'Jalisco', 'Guadalajara', 'Av. Mexico 2903, Guadalajara, CP 44690', 'restaurantes', 'fine_dining', 'Mexicana', 2026, 1, FALSE, TRUE, 'michelin_star', '1 Estrella MICHELIN 2026 | Nuevo 2026', 'gold_star', ARRAY['alcalde','michelin guadalajara','nuevo michelin jalisco'], 'https://guide.michelin.com/', 'verified', 'Nuevo en 2026.'),
('Xokol', 'MX', 'Jalisco', 'Guadalajara', 'Herrera y Cairo 1375, Santa Teresita, Guadalajara, CP 44600', 'restaurantes', 'fine_dining', 'Mexicana, Maiz nativo', 2026, 1, TRUE, TRUE, 'michelin_star_green', '1 Estrella MICHELIN 2026 + Estrella Verde | Nuevo 2026', 'gold_star_green_leaf', ARRAY['xokol','estrella verde guadalajara','michelin santa teresita'], 'https://guide.michelin.com/', 'verified', 'Nuevo en 2026 y estrella verde.'),
('KOLI Cocina de Origen', 'MX', 'Nuevo Leon', 'Monterrey', 'Rio Amazonas 225, Colonia Del Valle, Monterrey, CP 66220', 'restaurantes', 'fine_dining', 'Mexicana, Creativa', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['koli','michelin monterrey','alta cocina nuevo leon'], 'https://guide.michelin.com/', 'verified', ''),
('Pangea', 'MX', 'Nuevo Leon', 'San Pedro Garza Garcia', 'Av. del Roble 660, Valle del Campestre, San Pedro Garza Garcia, CP 66273', 'restaurantes', 'fine_dining', 'Actual, Mexicana', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['pangea','michelin san pedro','fine dining valle del campestre'], 'https://guide.michelin.com/', 'verified', ''),
('Los Danzantes Oaxaca', 'MX', 'Oaxaca', 'Oaxaca de Juarez', 'Macedonio Alcala 403, Interior 4, Colonia Centro, Oaxaca, CP 68000', 'restaurantes', 'fine_dining', 'Mexicana, Tradicional', 2026, 1, TRUE, FALSE, 'michelin_star_green', '1 Estrella MICHELIN 2026 + Estrella Verde', 'gold_star_green_leaf', ARRAY['los danzantes','estrella verde oaxaca','michelin centro oaxaca'], 'https://guide.michelin.com/', 'verified', ''),
('Levadura de Olla Restaurante', 'MX', 'Oaxaca', 'Oaxaca de Juarez', 'C. de Manuel Garcia Vigil 304, Oaxaca, CP 68000', 'restaurantes', 'fine_dining', 'Mexicana, Tradicional', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['levadura de olla','michelin oaxaca','restaurante premiado oaxaca'], 'https://guide.michelin.com/', 'verified', ''),
('Animalon', 'MX', 'Baja California', 'Valle de Guadalupe', 'Carr. Tecate-Ensenada Km. 83, Ejido Francisco Zarco, Valle de Guadalupe, CP 22750', 'restaurantes', 'fine_dining', 'Mexicana, Contemporanea', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['animalon','michelin valle de guadalupe','fine dining ensenada'], 'https://guide.michelin.com/', 'verified', ''),
('Conchas de Piedra', 'MX', 'Baja California', 'Valle de Guadalupe', 'Carr. Tecate Km. 93.5, Valle de Guadalupe, CP 22761', 'restaurantes', 'seafood_restaurant', 'Pescados y mariscos, Mexicana', 2026, 1, TRUE, FALSE, 'michelin_star_green', '1 Estrella MICHELIN 2026 + Estrella Verde', 'gold_star_green_leaf', ARRAY['conchas de piedra','mariscos michelin valle','estrella verde baja california'], 'https://guide.michelin.com/', 'verified', ''),
('Damiana', 'MX', 'Baja California', 'Valle de Guadalupe', 'Vinedos de la Reina, Mexico 3 Supermanzana, Km. 71, Valle de Guadalupe, CP 22034', 'restaurantes', 'fine_dining', 'Mexicana, Fusion', 2026, 1, TRUE, FALSE, 'michelin_star_green', '1 Estrella MICHELIN 2026 + Estrella Verde', 'gold_star_green_leaf', ARRAY['damiana','michelin valle de guadalupe','estrella verde valle'], 'https://guide.michelin.com/', 'verified', ''),
('Lunario', 'MX', 'Baja California', 'El Porvenir', 'Camino Vecinal Parcela 71 Fracc. 3 Lote 13, San Marcos, El Porvenir, CP 22750', 'restaurantes', 'fine_dining', 'Mexicana, Contemporanea', 2026, 1, TRUE, FALSE, 'michelin_star_green', '1 Estrella MICHELIN 2026 + Estrella Verde', 'gold_star_green_leaf', ARRAY['lunario','michelin el porvenir','estrella verde valle de guadalupe'], 'https://guide.michelin.com/', 'verified', ''),
('Olivea Farm to Table', 'MX', 'Baja California', 'Ensenada', 'Carr. Federal 3, Km. 92.5, Ruta del Vino Valle de Guadalupe, Ensenada, CP 22766', 'restaurantes', 'fine_dining', 'Actual, Contemporanea', 2026, 1, TRUE, FALSE, 'michelin_star_green', '1 Estrella MICHELIN 2026 + Estrella Verde', 'gold_star_green_leaf', ARRAY['olivea','farm to table ensenada','estrella verde ensenada'], 'https://guide.michelin.com/', 'verified', ''),
('Cocina de Autor Los Cabos', 'MX', 'Baja California Sur', 'Cabo San Lucas', 'Grand Velas Los Cabos, Carr. Transpeninsular Km. 17, San Jose del Cabo, Corredor Turistico, Cabo San Lucas, CP 23405', 'restaurantes', 'fine_dining', 'Mexicana', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['cocina de autor los cabos','michelin los cabos','fine dining cabo san lucas'], 'https://guide.michelin.com/', 'verified', ''),
('Cocina de Autor Riviera Maya', 'MX', 'Quintana Roo', 'Playa del Carmen', 'Grand Velas Riviera Maya, Carr. Cancun-Tulum Km. 62, Playa del Carmen, CP 77710', 'restaurantes', 'fine_dining', 'Creativa, Mexicana', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['cocina de autor riviera maya','michelin playa del carmen','fine dining riviera maya'], 'https://guide.michelin.com/', 'verified', ''),
('HA''', 'MX', 'Quintana Roo', 'Playa del Carmen', 'Hotel Xcaret, Carr. Chetumal-Puerto Juarez Kilometro 282, Solidaridad, Playa del Carmen, CP 77710', 'restaurantes', 'fine_dining', 'Mexicana, Contemporanea', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['ha','michelin xcaret','alta cocina playa del carmen'], 'https://guide.michelin.com/', 'verified', ''),
('Le Chique', 'MX', 'Quintana Roo', 'Playa del Carmen', 'Hotel Xcaret Arte, Carr. Chetumal-Puerto Juarez Km. 282 L21-3, Colonia Rancho Xcaret, Playa del Carmen, CP 77710', 'restaurantes', 'fine_dining', 'Contemporanea, Mexicana', 2026, 1, FALSE, FALSE, 'michelin_star', '1 Estrella MICHELIN 2026', 'gold_star', ARRAY['le chique','michelin xcaret arte','restaurante premiado riviera maya'], 'https://guide.michelin.com/', 'verified', ''),
('Huniik', 'MX', 'Yucatan', 'Merida', 'Calle 60 No. 415-B entre Calle 45 y Calle 47, Centro, Merida, CP 97000', 'restaurantes', 'fine_dining', 'Yucateca, Mexicana', 2026, 1, FALSE, TRUE, 'michelin_star', '1 Estrella MICHELIN 2026 | Nuevo 2026', 'gold_star', ARRAY['huniik','michelin merida','nuevo michelin yucatan'], 'https://guide.michelin.com/', 'verified', 'Nuevo en 2026.'),
('La Barra de Huniik', 'MX', 'Yucatan', 'Merida', 'C. 60 417, Parque Santa Ana, Centro, Merida, CP 97000', 'restaurantes', 'fine_dining', 'Yucateca, Mexicana', 2026, 1, FALSE, TRUE, 'michelin_star', '1 Estrella MICHELIN 2026 | Nuevo 2026', 'gold_star', ARRAY['la barra de huniik','michelin santa ana merida','nuevo michelin merida'], 'https://guide.michelin.com/', 'verified', 'Nuevo en 2026.'),
('Ixi''im', 'MX', 'Yucatan', 'Chochola', 'Chable Yucatan, Tablaje 642, San Antonio Chable, Chochola, CP 97816', 'restaurantes', 'fine_dining', 'Mexicana, Contemporanea, Maya', 2026, 1, TRUE, TRUE, 'michelin_star_green', '1 Estrella MICHELIN 2026 + Estrella Verde | Nuevo 2026', 'gold_star_green_leaf', ARRAY['ixiim','michelin chochola','estrella verde yucatan','maya michelin'], 'https://guide.michelin.com/', 'verified', 'Nuevo en 2026 y estrella verde.');

