export const ENTERPRISE_PROMO_END = '2026-08-01T23:59:59Z';

export const ENTERPRISE_FALLBACK_PRICING = [
  {
    code: 'city_launch',
    name: 'City Launch',
    description: '1 ciudad activa por 1 mes - ideal para validar mercado',
    regular_price_usd: 390,
    current_price_usd: 290,
    regular_price_mxn: 7020,
    current_price_mxn: 5220,
    discount_percent: 25,
    cities_included: 1,
    countries_included: 1,
    duration_months: 1,
    is_promo_active: true,
    promo_ends_at: ENTERPRISE_PROMO_END,
    features: ['1 ciudad activa', 'Busqueda patrocinada', '1 placement destacado en ciudad o categoria', 'Pin patrocinado en mapa', 'Dashboard basico']
  },
  {
    code: 'regional',
    name: 'Regional Pack',
    description: 'Hasta 5 ciudades activas en 2 paises, 3 meses de campaña',
    regular_price_usd: 2490,
    current_price_usd: 1990,
    regular_price_mxn: 44820,
    current_price_mxn: 35820,
    discount_percent: 20,
    cities_included: 5,
    countries_included: 2,
    duration_months: 3,
    is_promo_active: true,
    promo_ends_at: ENTERPRISE_PROMO_END,
    features: ['Hasta 5 ciudades activas', 'Rotacion de inventario patrocinado', 'Dashboard por ciudad', '2 optimizaciones incluidas', 'Soporte prioritario']
  },
  {
    code: 'country',
    name: 'Country Select',
    description: '1 pais, hasta 12 ciudades activas, 3 meses de campaña',
    regular_price_usd: 4900,
    current_price_usd: 3900,
    regular_price_mxn: 88200,
    current_price_mxn: 70200,
    discount_percent: 20,
    cities_included: 12,
    countries_included: 1,
    duration_months: 3,
    is_promo_active: true,
    promo_ends_at: ENTERPRISE_PROMO_END,
    features: ['Hasta 12 ciudades dentro de un pais', 'Placements premium en territorios seleccionados', 'Dashboard por ciudad/dispositivo/horario', 'Revision mensual de desempeño', 'Soporte prioritario']
  },
  {
    code: 'crossborder',
    name: 'Cross-Border Event',
    description: '2-3 paises o region especifica, campañas de 2-3 meses',
    regular_price_usd: 8900,
    current_price_usd: 6900,
    regular_price_mxn: 160200,
    current_price_mxn: 124200,
    discount_percent: 22,
    cities_included: 30,
    countries_included: 3,
    duration_months: 3,
    is_promo_active: true,
    promo_ends_at: ENTERPRISE_PROMO_END,
    features: ['2-3 paises o region continental', 'Segmentacion por idioma', 'Flight por evento o temporada', 'Reporte ejecutivo final', 'Soporte consultivo dedicado']
  },
  {
    code: 'global_custom',
    name: 'Global Custom',
    description: 'Cobertura multi-pais o continental, bajo propuesta personalizada',
    regular_price_usd: 9900,
    current_price_usd: 9900,
    regular_price_mxn: 178200,
    current_price_mxn: 178200,
    discount_percent: 0,
    cities_included: 999,
    countries_included: 999,
    duration_months: 3,
    is_promo_active: false,
    promo_ends_at: ENTERPRISE_PROMO_END,
    is_custom: true,
    features: ['Multi-pais o continental', 'Setup de campaña a medida', 'Inventario premium asignado', 'Reporting ejecutivo personalizado', 'Propuesta comercial y fiscal a medida']
  }
];
