// src/components/common/EconomicUrgencyCapsule.jsx
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { TrendingUp, ShieldAlert, Users, Compass, ArrowRight, CheckCircle2, XCircle } from 'lucide-react';
import { Link } from 'react-router-dom';

/**
 * Componente de Cápsulas Económicas y Posicionamiento vs Google Maps
 * Destaca la urgencia laboral, poder adquisitivo y el rol de Geobooker como motor económico local.
 */
export default function EconomicUrgencyCapsule({ showMatrix = true, compact = false }) {
  const { i18n } = useTranslation();
  const isSpanish = i18n.language === 'es' || !i18n.language.startsWith('en');
  const [activeTab, setActiveTab] = useState('pensions');

  const urgencyData = {
    pensions: {
      title: isSpanish ? 'La Realidad de las Pensiones' : 'The Pension Reality',
      stat: '64%',
      substat: isSpanish ? 'de los trabajadores globales no tendrán pensión suficiente (OIT)' : 'of global workers will lack adequate pensions (ILO)',
      quote: isSpanish
        ? 'Depender de una sola fuente de ingresos o del sistema tradicional es el mayor riesgo. Un negocio propio y rentable es tu seguro futuro.'
        : 'Relying on a single income stream or traditional systems is high risk. Your own profitable business is your future insurance.',
      icon: ShieldAlert,
      color: 'from-amber-500/20 to-red-500/20',
      borderColor: 'border-amber-500/40',
      badgeColor: 'bg-amber-500/10 text-amber-600 dark:text-amber-400'
    },
    purchasingPower: {
      title: isSpanish ? 'Poder Adquisitivo e Inflación' : 'Purchasing Power & Inflation',
      stat: '-22%',
      substat: isSpanish ? 'pérdida de capacidad de compra acumulada en 5 años' : 'cumulative loss in purchasing power over 5 years',
      quote: isSpanish
        ? 'Si tus ingresos no crecen con la economía local, trabajas más para comprar menos. Geobooker le da a tu negocio herramientas para captar clientes reales.'
        : 'If income does not keep up with local inflation, you work more for less. Geobooker gives your business tools to convert real clients.',
      icon: TrendingUp,
      color: 'from-blue-500/20 to-cyan-500/20',
      borderColor: 'border-blue-500/40',
      badgeColor: 'bg-blue-500/10 text-blue-600 dark:text-blue-400'
    },
    localEmployment: {
      title: isSpanish ? 'Sostén del Empleo Local' : 'Local Job Creation',
      stat: '58%',
      substat: isSpanish ? 'del empleo mundial se genera en PyMEs y comercios locales' : 'of global employment is generated by SMBs & local commerce',
      quote: isSpanish
        ? 'Un mapa te dice cómo llegar a una tienda. Geobooker ayuda a esa tienda a vender más, crecer y generar empleo en tu comunidad.'
        : 'A map shows how to reach a shop. Geobooker helps that shop convert sales, grow, and employ local people.',
      icon: Users,
      color: 'from-emerald-500/20 to-teal-500/20',
      borderColor: 'border-emerald-500/40',
      badgeColor: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400'
    }
  };

  const currentCapsule = urgencyData[activeTab];
  const IconComponent = currentCapsule.icon;

  return (
    <div className="w-full my-8 text-slate-800 dark:text-slate-100">
      {/* Header Badge */}
      <div className="text-center mb-6">
        <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold uppercase tracking-wider bg-sky-500/10 text-sky-600 dark:text-sky-400 border border-sky-500/20">
          <Compass className="w-3.5 h-3.5" />
          {isSpanish ? 'Posicionamiento & Realidad Económica' : 'Positioning & Economic Reality'}
        </span>
        <h2 className="text-2xl md:text-3xl font-extrabold mt-2 bg-gradient-to-r from-slate-900 via-sky-800 to-indigo-900 dark:from-white dark:via-sky-200 dark:to-indigo-200 bg-clip-text text-transparent">
          {isSpanish ? 'Más que un Mapa: Un Ecosistema Comercial Hiperlocal' : 'More Than a Map: A Hyperlocal Commercial Engine'}
        </h2>
        <p className="text-sm md:text-base text-slate-600 dark:text-slate-400 max-w-2xl mx-auto mt-1">
          {isSpanish
            ? 'Mientras las aplicaciones tradicionales se limitan a mostrar "dónde está y cómo llegar", Geobooker impulsa las ventas, la conversión y el empleo de los negocios de tu comunidad.'
            : 'While standard map apps only answer "where is it and how do I get there", Geobooker powers customer conversion, local business growth, and community jobs.'}
        </p>
      </div>

      {/* Tabs / Selector */}
      <div className="flex justify-center gap-2 mb-6 overflow-x-auto pb-2">
        {Object.entries(urgencyData).map(([key, data]) => (
          <button
            key={key}
            onClick={() => setActiveTab(key)}
            className={`px-4 py-2 rounded-xl text-xs md:text-sm font-semibold transition-all duration-200 flex items-center gap-2 whitespace-nowrap border ${
              activeTab === key
                ? 'bg-sky-600 text-white border-sky-600 shadow-md shadow-sky-500/20'
                : 'bg-white dark:bg-slate-800/80 text-slate-600 dark:text-slate-300 border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700/50'
            }`}
          >
            <data.icon className="w-4 h-4" />
            {data.title}
          </button>
        ))}
      </div>

      {/* Dynamic Urgency Card */}
      <div className={`relative overflow-hidden rounded-2xl p-6 md:p-8 bg-gradient-to-br ${currentCapsule.color} border ${currentCapsule.borderColor} backdrop-blur-md transition-all duration-300 shadow-lg`}>
        <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-center">
          <div className="md:col-span-4 text-center md:text-left">
            <span className={`inline-block px-3 py-1 rounded-md text-xs font-bold ${currentCapsule.badgeColor} mb-2`}>
              {currentCapsule.title}
            </span>
            <div className="text-4xl md:text-5xl font-black text-slate-900 dark:text-white tracking-tight">
              {currentCapsule.stat}
            </div>
            <p className="text-xs md:text-sm text-slate-600 dark:text-slate-300 font-medium mt-1">
              {currentCapsule.substat}
            </p>
          </div>

          <div className="md:col-span-8 flex flex-col justify-between">
            <blockquote className="text-sm md:text-base italic text-slate-800 dark:text-slate-200 border-l-4 border-sky-500 pl-4 py-1 mb-4">
              "{currentCapsule.quote}"
            </blockquote>

            <div className="flex flex-wrap items-center gap-3">
              <Link
                to="/reclamar-negocio"
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs md:text-sm font-bold bg-slate-900 text-white dark:bg-white dark:text-slate-900 hover:opacity-90 transition-opacity shadow-sm"
              >
                {isSpanish ? 'Reclamar Negocio Gratis' : 'Claim Free Profile'}
                <ArrowRight className="w-4 h-4" />
              </Link>
              <Link
                to="/emprende"
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs md:text-sm font-semibold bg-white/70 dark:bg-slate-800/70 text-slate-700 dark:text-slate-200 border border-slate-300 dark:border-slate-700 hover:bg-white dark:hover:bg-slate-800 transition-colors"
              >
                {isSpanish ? 'Ver Biblioteca Emprende' : 'Explore Emprende Guide'}
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Detailed Comparison Matrix (Optional) */}
      {showMatrix && (
        <div className="mt-10 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm">
          <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-4 text-center">
            {isSpanish ? 'Matriz Comparativa de Enfoque' : 'Approach Comparison Matrix'}
          </h3>
          <div className="overflow-x-auto">
            <table className="w-full text-xs md:text-sm text-left">
              <thead>
                <tr className="border-b border-slate-200 dark:border-slate-800 text-slate-500 dark:text-slate-400 font-semibold">
                  <th className="py-3 px-4">{isSpanish ? 'Dimensión' : 'Dimension'}</th>
                  <th className="py-3 px-4 bg-slate-50 dark:bg-slate-800/50 text-slate-700 dark:text-slate-300">Google Maps</th>
                  <th className="py-3 px-4 bg-sky-500/10 text-sky-700 dark:text-sky-300">Geobooker</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                <tr>
                  <td className="py-3 px-4 font-semibold text-slate-900 dark:text-slate-100">
                    {isSpanish ? 'Objetivo Central' : 'Core Objective'}
                  </td>
                  <td className="py-3 px-4 bg-slate-50 dark:bg-slate-800/50 text-slate-600 dark:text-slate-400">
                    {isSpanish ? 'Navegación GPS y localización' : 'GPS navigation & place lookup'}
                  </td>
                  <td className="py-3 px-4 bg-sky-500/5 text-sky-900 dark:text-sky-100 font-medium">
                    {isSpanish ? 'Conexión demanda-oferta y conversión' : 'Demand-to-supply matching & conversion'}
                  </td>
                </tr>
                <tr>
                  <td className="py-3 px-4 font-semibold text-slate-900 dark:text-slate-100">
                    {isSpanish ? 'Pregunta Clave' : 'Key Question'}
                  </td>
                  <td className="py-3 px-4 bg-slate-50 dark:bg-slate-800/50 text-slate-600 dark:text-slate-400">
                    {isSpanish ? '"¿Dónde está y cómo llego?"' : '"Where is it and how to get there?"'}
                  </td>
                  <td className="py-3 px-4 bg-sky-500/5 text-sky-900 dark:text-sky-100 font-medium">
                    {isSpanish ? '"¿Quién resuelve mi necesidad cerca?"' : '"Who can solve my specific need nearby?"'}
                  </td>
                </tr>
                <tr>
                  <td className="py-3 px-4 font-semibold text-slate-900 dark:text-slate-100">
                    {isSpanish ? 'Herramientas de Crecimiento' : 'Growth Tools'}
                  </td>
                  <td className="py-3 px-4 bg-slate-50 dark:bg-slate-800/50 text-slate-600 dark:text-slate-400 flex items-center gap-1">
                    <XCircle className="w-4 h-4 text-slate-400 shrink-0" />
                    {isSpanish ? 'Ficha pasiva / Google Ads' : 'Passive listing / Google Ads'}
                  </td>
                  <td className="py-3 px-4 bg-sky-500/5 text-sky-900 dark:text-sky-100 font-medium">
                    <div className="flex items-center gap-1">
                      <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                      {isSpanish ? 'CRM + Biblioteca + Emprende + Claims' : 'CRM + Biblioteca + Emprende + Verified Claims'}
                    </div>
                  </td>
                </tr>
                <tr>
                  <td className="py-3 px-4 font-semibold text-slate-900 dark:text-slate-100">
                    {isSpanish ? 'Impacto Económico' : 'Economic Impact'}
                  </td>
                  <td className="py-3 px-4 bg-slate-50 dark:bg-slate-800/50 text-slate-600 dark:text-slate-400">
                    {isSpanish ? 'Directorio de datos' : 'Data directory'}
                  </td>
                  <td className="py-3 px-4 bg-sky-500/5 text-sky-900 dark:text-sky-100 font-medium">
                    {isSpanish ? 'Generación de empleo y ventas locales' : 'Local job creation & sales engine'}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
