-- Expose `crm` through PostgREST configuration, but keep direct CRM access
-- restricted to backend service-role callers. The platform's exposed-schema
-- setting is managed separately; this migration owns database privileges.

DO $$
DECLARE
  override_value TEXT;
BEGIN
  SELECT config
    INTO override_value
  FROM pg_roles role_row
  CROSS JOIN LATERAL unnest(COALESCE(role_row.rolconfig, ARRAY[]::TEXT[])) AS config
  WHERE role_row.rolname = 'authenticator'
    AND config LIKE 'pgrst.db_schemas=%'
  LIMIT 1;

  IF override_value IS NOT NULL THEN
    RAISE NOTICE 'Resetting manual authenticator pgrst.db_schemas override so the platform Data API setting remains authoritative';
    ALTER ROLE authenticator RESET pgrst.db_schemas;
  ELSE
    RAISE NOTICE 'No manual authenticator pgrst.db_schemas override found';
  END IF;
END;
$$;

REVOKE ALL ON SCHEMA crm FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA crm TO service_role;

-- Remove inherited/historical direct CRM access for browser-facing roles.
REVOKE ALL ON ALL TABLES IN SCHEMA crm FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA crm FROM PUBLIC, anon, authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA crm
  REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA crm
  REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated;

-- The webhook never deletes provider or CRM records.
REVOKE DELETE ON TABLE
  crm.webhook_events,
  crm.messages,
  crm.message_status_events,
  crm.conversations,
  crm.activities,
  crm.contact_points,
  crm.whatsapp_phone_numbers,
  crm.whatsapp_business_accounts,
  crm.contacts,
  crm.channel_permissions,
  crm.usage_ledger
FROM service_role;

GRANT SELECT, INSERT, UPDATE ON TABLE
  crm.webhook_events,
  crm.messages,
  crm.message_status_events,
  crm.conversations,
  crm.contact_points,
  crm.whatsapp_phone_numbers,
  crm.whatsapp_business_accounts,
  crm.contacts,
  crm.channel_permissions,
  crm.usage_ledger
TO service_role;

GRANT SELECT, INSERT ON TABLE crm.activities TO service_role;

-- All webhook tables currently use UUID primary keys generated by
-- gen_random_uuid(); no table-owned sequences are required.

DO $$
DECLARE
  relation_name TEXT;
  relation_names CONSTANT TEXT[] := ARRAY[
    'webhook_events',
    'messages',
    'message_status_events',
    'conversations',
    'activities',
    'contact_points',
    'whatsapp_phone_numbers',
    'whatsapp_business_accounts',
    'contacts',
    'channel_permissions',
    'usage_ledger'
  ];
BEGIN
  IF has_schema_privilege('anon', 'crm', 'USAGE')
     OR has_schema_privilege('authenticated', 'crm', 'USAGE') THEN
    RAISE EXCEPTION 'CRM schema remains accessible to a browser-facing role';
  END IF;

  IF NOT has_schema_privilege('service_role', 'crm', 'USAGE') THEN
    RAISE EXCEPTION 'service_role lacks USAGE on crm';
  END IF;

  FOREACH relation_name IN ARRAY relation_names LOOP
    IF has_table_privilege('anon', format('crm.%I', relation_name), 'SELECT,INSERT,UPDATE,DELETE')
       OR has_table_privilege('authenticated', format('crm.%I', relation_name), 'SELECT,INSERT,UPDATE,DELETE') THEN
      RAISE EXCEPTION 'Browser-facing role retains direct privileges on crm.%', relation_name;
    END IF;

    IF has_table_privilege('service_role', format('crm.%I', relation_name), 'DELETE') THEN
      RAISE EXCEPTION 'service_role unexpectedly retains DELETE on crm.%', relation_name;
    END IF;
  END LOOP;
END;
$$;

NOTIFY pgrst, 'reload config';
NOTIFY pgrst, 'reload schema';
