-- GEOSCORE: Seed comercial México — 7 polos urbanos
-- Columnas reales de public.international_businesses (schema Amsterdam pilot)
-- Fuente: datos públicos Overture Maps / referencia pública.

BEGIN;

INSERT INTO public.international_businesses (
  owner_id, name, description, category, subcategory, address, city, state_code,
  postal_code, country_code, latitude, longitude, website, website_url, phone,
  slug, source_type, source_record_id, attribution_text, status, business_status,
  is_visible, is_claimed, is_verified, preferred_language, imported_at, updated_at
) VALUES

-- ================================================================
-- ZONA 1: CDMX — Polanco (~19.4326, ~-99.1908)
-- ================================================================
(NULL,'Pujol','Restaurante de alta cocina mexicana en Polanco.','restaurantes','restaurant','Tennyson 133, Polanco','Ciudad de México','CDMX','11550','MX',19.4312,-99.1976,'https://pujol.com.mx','https://pujol.com.mx','+525555454111','pujol-polanco-cdmx-gs001','seed_overture','gs-mx-pol-001','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Quintonil','Restaurante de cocina de autor mexicana.','restaurantes','restaurant','Newton 55, Polanco','Ciudad de México','CDMX','11560','MX',19.4331,-99.1958,'https://quintonil.com','https://quintonil.com','+525552804455','quintonil-polanco-cdmx-gs001','seed_overture','gs-mx-pol-002','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Liverpool Polanco','Tienda departamental Liverpool en Polanco.','tiendas','department_store','Mariano Escobedo 425, Polanco','Ciudad de México','CDMX','11560','MX',19.4344,-99.1927,'https://liverpool.com.mx','https://liverpool.com.mx','+525550629900','liverpool-polanco-cdmx-gs001','seed_overture','gs-mx-pol-003','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Antara Fashion Hall','Centro comercial premium en Polanco.','tiendas','shopping_center','Ejército Nacional 843B, Polanco','Ciudad de México','CDMX','11560','MX',19.4361,-99.1980,'https://antara.com.mx','https://antara.com.mx','+525555093700','antara-polanco-cdmx-gs001','seed_overture','gs-mx-pol-004','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Starbucks Masaryk','Cafetería Starbucks en Presidente Masaryk.','restaurantes','cafe','Presidente Masaryk 513, Polanco','Ciudad de México','CDMX','11560','MX',19.4321,-99.1948,'https://starbucks.com.mx','https://starbucks.com.mx',NULL,'starbucks-masaryk-polanco-gs001','seed_overture','gs-mx-pol-005','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Farmacia del Ahorro Polanco','Farmacia cadena en Polanco.','salud','pharmacy','Presidente Masaryk 410, Polanco','Ciudad de México','CDMX','11560','MX',19.4319,-99.1933,'https://fahorro.com','https://fahorro.com','+528007996600','farmacia-ahorro-polanco-gs001','seed_overture','gs-mx-pol-006','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Santander Polanco','Banco Santander en Polanco.','servicios','bank','Emilio Castelar 75, Polanco','Ciudad de México','CDMX','11560','MX',19.4327,-99.1921,'https://santander.com.mx','https://santander.com.mx','+528001234321','santander-polanco-cdmx-gs001','seed_overture','gs-mx-pol-007','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'HSBC Polanco','Banco HSBC en Polanco.','servicios','bank','Presidente Masaryk 360, Polanco','Ciudad de México','CDMX','11560','MX',19.4316,-99.1940,'https://hsbc.com.mx','https://hsbc.com.mx','+528007126900','hsbc-polanco-cdmx-gs001','seed_overture','gs-mx-pol-008','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Banamex Polanco','Banco Citibanamex en Polanco.','servicios','bank','Presidente Masaryk 290, Polanco','Ciudad de México','CDMX','11560','MX',19.4314,-99.1935,'https://citibanamex.com','https://citibanamex.com','+528002265555','banamex-polanco-cdmx-gs001','seed_overture','gs-mx-pol-009','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Supra Gym Polanco','Gimnasio en Polanco.','deporte','gym','Horacio 1855, Polanco','Ciudad de México','CDMX','11550','MX',19.4308,-99.1944,'https://supragym.com.mx','https://supragym.com.mx','+525552805050','supra-gym-polanco-gs001','seed_overture','gs-mx-pol-010','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Superama Polanco','Supermercado en Polanco.','tiendas','supermarket','Ejército Nacional 769, Polanco','Ciudad de México','CDMX','11550','MX',19.4350,-99.1966,'https://walmart.com.mx','https://walmart.com.mx','+525555578100','superama-polanco-cdmx-gs001','seed_overture','gs-mx-pol-011','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Sushi Itto Polanco','Restaurante japonés en Polanco.','restaurantes','restaurant','Emilio Castelar 95, Polanco','Ciudad de México','CDMX','11560','MX',19.4322,-99.1920,'https://sushiitto.com.mx','https://sushiitto.com.mx','+525552532388','sushi-itto-polanco-gs001','seed_overture','gs-mx-pol-012','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Balmori Suites Polanco','Hotel boutique en Polanco.','hospedaje','hotel','Julio Verne 35, Polanco','Ciudad de México','CDMX','11550','MX',19.4298,-99.1965,'https://balmori.com.mx','https://balmori.com.mx','+525552509000','balmori-suites-polanco-gs001','seed_overture','gs-mx-pol-013','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Oxxo Masaryk Polanco','Tienda de conveniencia Oxxo en Polanco.','tiendas','convenience_store','Presidente Masaryk 480, Polanco','Ciudad de México','CDMX','11560','MX',19.4323,-99.1944,NULL,NULL,NULL,'oxxo-masaryk-polanco-gs001','seed_overture','gs-mx-pol-014','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Clínica Médica Polanco','Clínica médica privada en Polanco.','salud','clinic','Molière 425, Polanco','Ciudad de México','CDMX','11560','MX',19.4329,-99.1969,NULL,NULL,NULL,'clinica-medica-polanco-gs001','seed_overture','gs-mx-pol-015','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),

-- ================================================================
-- ZONA 2: CDMX — Roma / Condesa (~19.4168, ~-99.1712)
-- ================================================================
(NULL,'Panadería Rosetta','Panadería y cafetería en Roma Norte.','restaurantes','bakery','Colima 179, Roma Norte','Ciudad de México','CDMX','06700','MX',19.4191,-99.1601,'https://rosetta.com.mx','https://rosetta.com.mx','+525552072976','panaderia-rosetta-roma-gs001','seed_overture','gs-mx-rom-001','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Hotel Condesa DF','Hotel boutique en la Condesa.','hospedaje','hotel','Av. Veracruz 102, Condesa','Ciudad de México','CDMX','06140','MX',19.4168,-99.1712,'https://condesadf.com','https://condesadf.com','+525552412600','hotel-condesa-df-gs001','seed_overture','gs-mx-rom-002','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Librería El Péndulo Condesa','Librería y cafetería en la Condesa.','tiendas','bookstore','Nuevo León 115, Condesa','Ciudad de México','CDMX','06140','MX',19.4132,-99.1704,'https://pendulo.com','https://pendulo.com','+525552869494','libreria-pendulo-condesa-gs001','seed_overture','gs-mx-rom-003','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Farmacia Guadalajara Roma','Farmacia cadena en Roma Norte.','salud','pharmacy','Álvaro Obregón 80, Roma Norte','Ciudad de México','CDMX','06700','MX',19.4182,-99.1618,'https://farmaciasguadalajara.com','https://farmaciasguadalajara.com','+528008008000','farmacia-gdl-roma-gs001','seed_overture','gs-mx-rom-004','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'BBVA Roma Norte','Banco BBVA en Roma Norte.','servicios','bank','Ámsterdam 160, Roma Norte','Ciudad de México','CDMX','06700','MX',19.4172,-99.1660,'https://bbva.mx','https://bbva.mx','+528006642224','bbva-roma-norte-gs001','seed_overture','gs-mx-rom-005','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Smart Fit Condesa','Gimnasio Smart Fit en la Condesa.','deporte','gym','Av. México 127, Condesa','Ciudad de México','CDMX','06140','MX',19.4155,-99.1726,'https://smartfit.com.mx','https://smartfit.com.mx','+525553505000','smartfit-condesa-gs001','seed_overture','gs-mx-rom-006','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Oxxo Jalapa Roma Norte','Tienda de conveniencia en Roma Norte.','tiendas','convenience_store','Jalapa 80, Roma Norte','Ciudad de México','CDMX','06700','MX',19.4201,-99.1632,NULL,NULL,NULL,'oxxo-jalapa-roma-gs001','seed_overture','gs-mx-rom-007','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Mercado de Medellín','Mercado tradicional en Roma Sur.','tiendas','market','Campeche 101, Roma Sur','Ciudad de México','CDMX','06700','MX',19.4132,-99.1658,NULL,NULL,NULL,'mercado-medellin-roma-gs001','seed_overture','gs-mx-rom-008','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Santander Condesa','Banco Santander en la Condesa.','servicios','bank','Ámsterdam 264, Condesa','Ciudad de México','CDMX','06140','MX',19.4145,-99.1715,'https://santander.com.mx','https://santander.com.mx','+528001234321','santander-condesa-gs001','seed_overture','gs-mx-rom-009','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Metro Insurgentes','Estación de metro en Roma Norte.','servicios','transit','Insurgentes Centro, Roma Norte','Ciudad de México','CDMX','06700','MX',19.4160,-99.1670,NULL,NULL,NULL,'metro-insurgentes-gs001','seed_overture','gs-mx-rom-010','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Suburbia Insurgentes','Tienda de ropa Suburbia en Roma.','tiendas','retail','Insurgentes Sur 553, Roma','Ciudad de México','CDMX','06700','MX',19.4122,-99.1692,NULL,NULL,NULL,'suburbia-insurgentes-gs001','seed_overture','gs-mx-rom-011','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Café Toscano Roma','Cafetería en Roma Norte.','restaurantes','cafe','Orizaba 42, Roma Norte','Ciudad de México','CDMX','06700','MX',19.4195,-99.1620,NULL,NULL,NULL,'cafe-toscano-roma-gs001','seed_overture','gs-mx-rom-012','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),

-- ================================================================
-- ZONA 3: CDMX — Centro Histórico (~19.4326, ~-99.1332)
-- ================================================================
(NULL,'Café de Tacuba','Restaurante histórico en el Centro.','restaurantes','restaurant','Tacuba 28, Centro Histórico','Ciudad de México','CDMX','06000','MX',19.4357,-99.1378,'https://cafedetacuba.com.mx','https://cafedetacuba.com.mx','+525555184950','cafe-tacuba-centro-gs001','seed_overture','gs-mx-cen-001','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Palacio de Hierro Centro','Tienda departamental en Centro Histórico.','tiendas','department_store','20 de Noviembre 3, Centro','Ciudad de México','CDMX','06000','MX',19.4288,-99.1365,'https://elpalaciodehierro.com','https://elpalaciodehierro.com','+525558002800','palacio-hierro-centro-gs001','seed_overture','gs-mx-cen-002','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Gran Hotel Ciudad de México','Hotel histórico en el Centro.','hospedaje','hotel','16 de Septiembre 82, Centro','Ciudad de México','CDMX','06000','MX',19.4325,-99.1325,'https://granhotelciudaddemexico.com.mx','https://granhotelciudaddemexico.com.mx','+525252831053','gran-hotel-cdmx-gs001','seed_overture','gs-mx-cen-003','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'BBVA Centro Histórico','Banco BBVA en Centro Histórico.','servicios','bank','5 de Mayo 15, Centro','Ciudad de México','CDMX','06010','MX',19.4335,-99.1345,'https://bbva.mx','https://bbva.mx','+528006642224','bbva-centro-historico-gs001','seed_overture','gs-mx-cen-004','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Sanborns Casa de los Azulejos','Restaurante y tienda emblemática en el Centro.','restaurantes','restaurant','Madero 4, Centro','Ciudad de México','CDMX','06000','MX',19.4334,-99.1339,'https://sanborns.com.mx','https://sanborns.com.mx','+525555126676','sanborns-azulejos-centro-gs001','seed_overture','gs-mx-cen-005','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Farmacia Benavides Centro','Farmacia cadena en Centro Histórico.','salud','pharmacy','Madero 14, Centro','Ciudad de México','CDMX','06000','MX',19.4331,-99.1348,'https://benavides.com.mx','https://benavides.com.mx',NULL,'farmacia-benavides-centro-gs001','seed_overture','gs-mx-cen-006','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Metro Zócalo','Estación de metro Zócalo Línea 2.','servicios','transit','Plaza de la Constitución, Centro','Ciudad de México','CDMX','06000','MX',19.4326,-99.1332,NULL,NULL,NULL,'metro-zocalo-gs001','seed_overture','gs-mx-cen-007','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Banamex Centro Histórico','Banco Citibanamex en Centro.','servicios','bank','Isabel La Católica 44, Centro','Ciudad de México','CDMX','06000','MX',19.4320,-99.1350,'https://citibanamex.com','https://citibanamex.com','+528002265555','banamex-centro-historico-gs001','seed_overture','gs-mx-cen-008','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Oxxo Zócalo Centro','Tienda de conveniencia en el Zócalo.','tiendas','convenience_store','Guatemala 1, Centro','Ciudad de México','CDMX','06000','MX',19.4326,-99.1332,NULL,NULL,NULL,'oxxo-zocalo-centro-gs001','seed_overture','gs-mx-cen-009','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Soriana Express Centro','Supermercado Soriana en Centro.','tiendas','supermarket','Mesones 40, Centro','Ciudad de México','CDMX','06020','MX',19.4298,-99.1332,'https://soriana.com','https://soriana.com','+528007676000','soriana-centro-historico-gs001','seed_overture','gs-mx-cen-010','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Hotel Histórico Central','Hotel en Centro Histórico.','hospedaje','hotel','Uruguay 106, Centro','Ciudad de México','CDMX','06000','MX',19.4308,-99.1378,NULL,NULL,'+525255225464','hotel-historico-central-gs001','seed_overture','gs-mx-cen-011','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Librería Porrúa Centro','Librería en Centro Histórico.','tiendas','bookstore','Argentina 1, Centro','Ciudad de México','CDMX','06000','MX',19.4337,-99.1315,'https://porrua.mx','https://porrua.mx','+525555469160','libreria-porrua-centro-gs001','seed_overture','gs-mx-cen-012','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),

-- ================================================================
-- ZONA 4: Guadalajara — Providencia (~20.6866, ~-103.3876)
-- ================================================================
(NULL,'Casa Bariachi Providencia','Restaurante con mariachi en Providencia.','restaurantes','restaurant','Av. de las Américas 618, Providencia','Guadalajara','Jalisco','44620','MX',20.6878,-103.3855,'https://casabariachi.com.mx','https://casabariachi.com.mx','+523338260993','casa-bariachi-providencia-gs001','seed_overture','gs-mx-gdl-001','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Liverpool Providencia Guadalajara','Tienda departamental en Providencia.','tiendas','department_store','Av. Américas 1233, Providencia','Guadalajara','Jalisco','44620','MX',20.6851,-103.3891,'https://liverpool.com.mx','https://liverpool.com.mx','+523339525900','liverpool-providencia-gdl-gs001','seed_overture','gs-mx-gdl-002','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Starbucks Providencia Guadalajara','Cafetería Starbucks en Providencia.','restaurantes','cafe','Juan Palomar y Arias 800, Providencia','Guadalajara','Jalisco','44620','MX',20.6871,-103.3872,NULL,NULL,NULL,'starbucks-providencia-gdl-gs001','seed_overture','gs-mx-gdl-003','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'BBVA Providencia Guadalajara','Banco BBVA en Providencia.','servicios','bank','Av. Américas 955, Providencia','Guadalajara','Jalisco','44620','MX',20.6862,-103.3878,'https://bbva.mx','https://bbva.mx','+528006642224','bbva-providencia-gdl-gs001','seed_overture','gs-mx-gdl-004','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Farmacia del Ahorro Providencia Gdl','Farmacia cadena en Providencia.','salud','pharmacy','Manuel Acuña 2598, Providencia','Guadalajara','Jalisco','44620','MX',20.6880,-103.3868,'https://fahorro.com','https://fahorro.com','+528007996600','farmacia-ahorro-providencia-gdl-gs001','seed_overture','gs-mx-gdl-005','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Smart Fit Providencia Guadalajara','Gimnasio Smart Fit en Providencia.','deporte','gym','Av. de las Américas 1200, Providencia','Guadalajara','Jalisco','44620','MX',20.6849,-103.3885,'https://smartfit.com.mx','https://smartfit.com.mx',NULL,'smartfit-providencia-gdl-gs001','seed_overture','gs-mx-gdl-006','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Oxxo Providencia Américas','Tienda de conveniencia en Providencia.','tiendas','convenience_store','Av. de las Américas 890, Providencia','Guadalajara','Jalisco','44620','MX',20.6864,-103.3880,NULL,NULL,NULL,'oxxo-providencia-americas-gs001','seed_overture','gs-mx-gdl-007','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Santander Providencia Guadalajara','Banco Santander en Providencia.','servicios','bank','Av. Américas 1071, Providencia','Guadalajara','Jalisco','44630','MX',20.6866,-103.3877,'https://santander.com.mx','https://santander.com.mx','+528001234321','santander-providencia-gdl-gs001','seed_overture','gs-mx-gdl-008','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Cinépolis Providencia Guadalajara','Cine Cinépolis en Providencia.','entretenimiento','cinema','Av. Américas 1233 P2, Providencia','Guadalajara','Jalisco','44620','MX',20.6850,-103.3892,'https://cinepolis.com','https://cinepolis.com',NULL,'cinepolis-providencia-gdl-gs001','seed_overture','gs-mx-gdl-009','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Soriana Providencia Guadalajara','Supermercado Soriana en Providencia.','tiendas','supermarket','Av. Américas 799, Providencia','Guadalajara','Jalisco','44630','MX',20.6860,-103.3872,'https://soriana.com','https://soriana.com','+528007676000','soriana-providencia-gdl-gs001','seed_overture','gs-mx-gdl-010','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Autolavado La Joya Guadalajara','Autolavado en Providencia.','hogar_autos','car_wash','Manuel Acuña 2740, Providencia','Guadalajara','Jalisco','44620','MX',20.6885,-103.3862,NULL,NULL,NULL,'autolavado-la-joya-gdl-gs001','seed_overture','gs-mx-gdl-011','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Hotel Presidente InterContinental Gdl','Hotel de lujo en Guadalajara.','hospedaje','hotel','Av. López Mateos Sur 3515, Guadalajara','Guadalajara','Jalisco','44100','MX',20.6855,-103.3845,'https://ihg.com','https://ihg.com','+523336785050','hotel-presidente-intercont-gdl-gs001','seed_overture','gs-mx-gdl-012','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),

-- ================================================================
-- ZONA 5: Monterrey — San Pedro Garza García (~25.6594, ~-100.3689)
-- ================================================================
(NULL,'Restaurante Pangea Monterrey','Restaurante de alta cocina en Valle Oriente.','restaurantes','restaurant','Ave. Silla 830, Valle Oriente','San Pedro Garza García','Nuevo León','66220','MX',25.6540,-100.3638,'https://pangea.com.mx','https://pangea.com.mx','+528180028020','restaurante-pangea-mty-gs001','seed_overture','gs-mx-mty-001','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Liverpool San Pedro Monterrey','Tienda departamental en San Pedro.','tiendas','department_store','Av. Gómez Morín 700, La Muralla','San Pedro Garza García','Nuevo León','66220','MX',25.6580,-100.3652,'https://liverpool.com.mx','https://liverpool.com.mx','+528180409900','liverpool-san-pedro-mty-gs001','seed_overture','gs-mx-mty-002','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Starbucks Valle Oriente Monterrey','Cafetería Starbucks en Valle Oriente.','restaurantes','cafe','Ave. Batallón de San Patricio 111, San Pedro','San Pedro Garza García','Nuevo León','66210','MX',25.6601,-100.3680,NULL,NULL,NULL,'starbucks-valle-oriente-mty-gs001','seed_overture','gs-mx-mty-003','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'BBVA San Pedro Monterrey','Banco BBVA en San Pedro.','servicios','bank','Av. Vasconcelos 150 Ote, San Pedro','San Pedro Garza García','Nuevo León','66220','MX',25.6598,-100.3672,'https://bbva.mx','https://bbva.mx','+528006642224','bbva-san-pedro-mty-gs001','seed_overture','gs-mx-mty-004','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Farmacia del Ahorro San Pedro Monterrey','Farmacia cadena en San Pedro.','salud','pharmacy','Av. Revolución 2703, San Pedro','San Pedro Garza García','Nuevo León','66220','MX',25.6588,-100.3695,'https://fahorro.com','https://fahorro.com','+528007996600','farmacia-ahorro-san-pedro-mty-gs001','seed_overture','gs-mx-mty-005','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Smart Fit San Pedro Monterrey','Gimnasio Smart Fit en San Pedro.','deporte','gym','Gómez Morín 800, San Pedro','San Pedro Garza García','Nuevo León','66220','MX',25.6582,-100.3665,NULL,NULL,NULL,'smartfit-san-pedro-mty-gs001','seed_overture','gs-mx-mty-006','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Marriott Monterrey Valle','Hotel Marriott en Del Valle.','hospedaje','hotel','Ave. Río Nilo 160, Del Valle','Monterrey','Nuevo León','64750','MX',25.6544,-100.3635,'https://marriott.com','https://marriott.com','+528183785555','marriott-monterrey-valle-gs001','seed_overture','gs-mx-mty-007','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Oxxo San Pedro Centro Monterrey','Tienda de conveniencia en San Pedro.','tiendas','convenience_store','Av. Vasconcelos 300, San Pedro','San Pedro Garza García','Nuevo León','66230','MX',25.6592,-100.3680,NULL,NULL,NULL,'oxxo-san-pedro-centro-mty-gs001','seed_overture','gs-mx-mty-008','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Walmart San Pedro Garza García','Supermercado Walmart en San Pedro.','tiendas','supermarket','Lázaro Garza Ayala 1650, San Pedro','San Pedro Garza García','Nuevo León','66220','MX',25.6611,-100.3720,'https://walmart.com.mx','https://walmart.com.mx','+528007676000','walmart-san-pedro-mty-gs001','seed_overture','gs-mx-mty-009','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Santander San Pedro Monterrey','Banco Santander en San Pedro.','servicios','bank','Av. Vasconcelos 200, San Pedro','San Pedro Garza García','Nuevo León','66220','MX',25.6595,-100.3676,'https://santander.com.mx','https://santander.com.mx','+528001234321','santander-san-pedro-mty-gs001','seed_overture','gs-mx-mty-010','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Cinépolis VIP Gómez Morín','Cine Cinépolis en San Pedro.','entretenimiento','cinema','Av. Gómez Morín 820','San Pedro Garza García','Nuevo León','66220','MX',25.6583,-100.3659,NULL,NULL,NULL,'cinepolis-vip-gomez-morin-gs001','seed_overture','gs-mx-mty-011','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Taquería La Única San Pedro','Taquería local en San Pedro.','restaurantes','restaurant','Revolución 3041, San Pedro','San Pedro Garza García','Nuevo León','66220','MX',25.6576,-100.3699,NULL,NULL,NULL,'taqueria-la-unica-san-pedro-gs001','seed_overture','gs-mx-mty-012','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),

-- ================================================================
-- ZONA 6: Puebla — Angelópolis (~19.0187, ~-98.2365)
-- ================================================================
(NULL,'Centro Comercial Angelópolis','Centro comercial en Angelópolis.','tiendas','shopping_center','Blvd. del Niño Poblano 2510, Angelópolis','Puebla','Puebla','72830','MX',19.0178,-98.2350,'https://angelopolis.com.mx','https://angelopolis.com.mx','+522222855555','cc-angelopolis-pue-gs001','seed_overture','gs-mx-pue-001','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Liverpool Angelópolis Puebla','Tienda departamental en Angelópolis.','tiendas','department_store','Blvd. del Niño Poblano 2510 L4','Puebla','Puebla','72830','MX',19.0179,-98.2348,'https://liverpool.com.mx','https://liverpool.com.mx','+522228350900','liverpool-angelopolis-pue-gs001','seed_overture','gs-mx-pue-002','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Starbucks Angelópolis Puebla','Cafetería Starbucks en Angelópolis.','restaurantes','cafe','Blvd. del Niño Poblano 2510 P1','Puebla','Puebla','72820','MX',19.0180,-98.2352,NULL,NULL,NULL,'starbucks-angelopolis-pue-gs001','seed_overture','gs-mx-pue-003','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'BBVA Angelópolis Puebla','Banco BBVA en Angelópolis.','servicios','bank','Blvd. del Niño Poblano 2590, Angelópolis','Puebla','Puebla','72820','MX',19.0185,-98.2362,'https://bbva.mx','https://bbva.mx','+528006642224','bbva-angelopolis-pue-gs001','seed_overture','gs-mx-pue-004','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Farmacia del Ahorro Angelópolis','Farmacia cadena en Angelópolis.','salud','pharmacy','Blvd. del Niño Poblano 2600','Puebla','Puebla','72820','MX',19.0183,-98.2360,'https://fahorro.com','https://fahorro.com','+528007996600','farmacia-ahorro-angelopolis-pue-gs001','seed_overture','gs-mx-pue-005','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Smart Fit Angelópolis Puebla','Gimnasio Smart Fit en Angelópolis.','deporte','gym','Via Atlixcáyotl 5200, Angelópolis','Puebla','Puebla','72820','MX',19.0165,-98.2375,NULL,NULL,NULL,'smartfit-angelopolis-pue-gs001','seed_overture','gs-mx-pue-006','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Cinépolis Angelópolis Puebla','Cine Cinépolis en Angelópolis.','entretenimiento','cinema','Blvd. del Niño Poblano 2510 P3','Puebla','Puebla','72830','MX',19.0177,-98.2348,NULL,NULL,NULL,'cinepolis-angelopolis-pue-gs001','seed_overture','gs-mx-pue-007','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Soriana Angelópolis Puebla','Supermercado Soriana en Angelópolis.','tiendas','supermarket','Via Atlixcáyotl 5900, Angelópolis','Puebla','Puebla','72820','MX',19.0159,-98.2390,'https://soriana.com','https://soriana.com','+528007676000','soriana-angelopolis-pue-gs001','seed_overture','gs-mx-pue-008','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Autolavado Wash Center Puebla','Autolavado en Angelópolis.','hogar_autos','car_wash','Blvd. del Niño Poblano 2700','Puebla','Puebla','72820','MX',19.0188,-98.2368,NULL,NULL,NULL,'autolavado-wash-center-pue-gs001','seed_overture','gs-mx-pue-009','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Santander Angelópolis Puebla','Banco Santander en Angelópolis.','servicios','bank','Via Atlixcáyotl 4620','Puebla','Puebla','72820','MX',19.0168,-98.2372,'https://santander.com.mx','https://santander.com.mx','+528001234321','santander-angelopolis-pue-gs001','seed_overture','gs-mx-pue-010','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Oxxo Angelópolis Puebla','Tienda de conveniencia en Angelópolis.','tiendas','convenience_store','Blvd. del Niño Poblano 2400','Puebla','Puebla','72820','MX',19.0190,-98.2340,NULL,NULL,NULL,'oxxo-angelopolis-pue-gs001','seed_overture','gs-mx-pue-011','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Hotel City Express Angelópolis','Hotel de negocios en Angelópolis.','hospedaje','hotel','Via Atlixcáyotl 3900','Puebla','Puebla','72820','MX',19.0171,-98.2380,'https://cityexpress.com.mx','https://cityexpress.com.mx','+522223032400','hotel-city-express-angelopolis-gs001','seed_overture','gs-mx-pue-012','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),

-- ================================================================
-- ZONA 7: Cancún — Zona Hotelera (~21.0620, ~-86.8470)
-- ================================================================
(NULL,'Hotel Marriott Cancún Resort','Hotel resort de lujo en Zona Hotelera.','hospedaje','hotel','Blvd Kukulcan Km 14.5, Zona Hotelera','Cancún','Quintana Roo','77500','MX',21.0610,-86.7888,'https://marriott.com','https://marriott.com','+529988818200','marriott-cancun-resort-gs001','seed_overture','gs-mx-cun-001','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'La Isla Shopping Village Cancún','Centro comercial en Zona Hotelera.','tiendas','shopping_center','Blvd Kukulcan Km 12.5, Zona Hotelera','Cancún','Quintana Roo','77500','MX',21.0640,-86.7930,'https://laislacancun.com.mx','https://laislacancun.com.mx','+529988830403','la-isla-cancun-gs001','seed_overture','gs-mx-cun-002','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Starbucks La Isla Cancún','Cafetería Starbucks en La Isla Cancún.','restaurantes','cafe','Blvd Kukulcan Km 12.5 L-37','Cancún','Quintana Roo','77500','MX',21.0641,-86.7929,NULL,NULL,NULL,'starbucks-la-isla-cancun-gs001','seed_overture','gs-mx-cun-003','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'BBVA Cancún Zona Hotelera','Banco BBVA en Zona Hotelera.','servicios','bank','Blvd Kukulcan Km 8.5, Zona Hotelera','Cancún','Quintana Roo','77500','MX',21.0702,-86.8166,'https://bbva.mx','https://bbva.mx','+528006642224','bbva-cancun-zona-hotelera-gs001','seed_overture','gs-mx-cun-004','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Farmacia Similares Zona Hotelera','Farmacia Similares en Zona Hotelera.','salud','pharmacy','Blvd Kukulcan Km 9.5, Zona Hotelera','Cancún','Quintana Roo','77500','MX',21.0683,-86.8124,NULL,NULL,NULL,'farmacia-similares-cancun-zh-gs001','seed_overture','gs-mx-cun-005','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Walmart Cancún Zona Hotelera','Supermercado Walmart en Zona Hotelera.','tiendas','supermarket','Blvd Kukulcan Km 9, Zona Hotelera','Cancún','Quintana Roo','77500','MX',21.0688,-86.8138,'https://walmart.com.mx','https://walmart.com.mx','+528007676000','walmart-cancun-zh-gs001','seed_overture','gs-mx-cun-006','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Oxxo Zona Hotelera Km 10','Tienda de conveniencia en Zona Hotelera.','tiendas','convenience_store','Blvd Kukulcan Km 10, Zona Hotelera','Cancún','Quintana Roo','77500','MX',21.0665,-86.8074,NULL,NULL,NULL,'oxxo-zona-hotelera-km10-gs001','seed_overture','gs-mx-cun-007','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Chedraui Cancún Zona Hotelera','Supermercado Chedraui en Zona Hotelera.','tiendas','supermarket','Blvd Kukulcan Km 9.6, Zona Hotelera','Cancún','Quintana Roo','77500','MX',21.0674,-86.8115,'https://chedraui.com.mx','https://chedraui.com.mx','+529983810100','chedraui-cancun-zh-gs001','seed_overture','gs-mx-cun-008','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Smart Fit Cancún','Gimnasio Smart Fit en Cancún.','deporte','gym','Av. López Portillo 289, SM 81','Cancún','Quintana Roo','77506','MX',21.1578,-86.8356,NULL,NULL,NULL,'smartfit-cancun-gs001','seed_overture','gs-mx-cun-009','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Palacio de Hierro Cancún La Isla','Tienda departamental en La Isla.','tiendas','department_store','Blvd Kukulcan Km 12.5 La Isla','Cancún','Quintana Roo','77500','MX',21.0639,-86.7928,'https://elpalaciodehierro.com','https://elpalaciodehierro.com','+529988833900','palacio-hierro-cancun-gs001','seed_overture','gs-mx-cun-010','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'Autolavado Aqua Cancún','Autolavado en Zona Hotelera.','hogar_autos','car_wash','Blvd Kukulcan Km 11, Zona Hotelera','Cancún','Quintana Roo','77500','MX',21.0656,-86.8001,NULL,NULL,NULL,'autolavado-aqua-cancun-gs001','seed_overture','gs-mx-cun-011','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW()),
(NULL,'La Habichuela Downtown Cancún','Restaurante de mariscos en el Centro de Cancún.','restaurantes','restaurant','Margaritas 25, Centro Cancún','Cancún','Quintana Roo','77500','MX',21.1601,-86.8485,'https://lahabichuela.com','https://lahabichuela.com','+529988843158','la-habichuela-downtown-cancun-gs001','seed_overture','gs-mx-cun-012','Overture Maps / GeoScore Seed MX 2026','approved','active',TRUE,FALSE,FALSE,'es',NOW(),NOW())

ON CONFLICT (source_record_id) DO NOTHING;

-- Verificación
DO $$
DECLARE v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM public.international_businesses
  WHERE source_record_id LIKE 'gs-mx-%';
  RAISE NOTICE 'GeoScore MX seed: % negocios insertados', v_count;
END;
$$;

NOTIFY pgrst, 'reload schema';
COMMIT;
